### PR TITLE
For arrays of arrays, we can get a `ProgMem` for an inner one #8

### PR DESCRIPTION
**Pull request by gergoerdi**

### CODE REVIEW

**Comment by gergoerdi** [comment]
As discussed in #8. I'm not sure about the name `offset_at`. Wouldn't it even make sense to allow normal indexing (i.e. `MY_PROGMEM[i]`) for this, since it involves no explicit loading between progmem data and RAM data?

**Comment by Cryptjar** [comment]
I think a simple `get` would do well enough as the function name. Also, I think, there is no point in over-constraining this function, and it should be fine if you implement it just on `ProgMem<[T; N]>` returning a simple `ProgMem<T>` (because `T` may also be another array).

However, about the "normal" indexing, I'm afraid that it will not be an option, because the [`Index` trait](https://doc.rust-lang.org/std/ops/trait.Index.html) (that enables the `container[index]` operation) requires that a reference is returned, and that is simply not possible here.

Also, you should run `cargo +nightly fmt`.

**Comment by Cryptjar** [comment]
Looks good, thanks.

**Comment by Cryptjar** [comment]
Released as part of `v0.3.2`

**Pull request merged**
